export const titleColors = [
  "text-black",
  "text-white",
  "text-gray-100", // For a very light gray that is close to white
  "text-gray-900", // For a very dark gray that is close to black
  "text-blue-500",
  "text-blue-600",
  "text-blue-700",
  "text-indigo-500",
  "text-indigo-600",
  "text-indigo-700",
  "text-purple-500",
  "text-purple-600",
  "text-purple-700",
  "text-green-500",
  "text-green-600",
  "text-green-700",
  "text-teal-500",
  "text-teal-600",
  "text-teal-700",
  "text-red-500",
  "text-red-600",
  "text-red-700",
  "text-orange-500",
  "text-orange-600",
  "text-orange-700",
  "text-yellow-500",
  "text-yellow-600",
  "text-yellow-700",
  "text-pink-500",
  "text-pink-600",
  "text-pink-700",
  "text-gray-500",
  "text-gray-600",
  "text-gray-700",
];

export const backgroundColors = [
  "bg-black",
  "bg-white",
  "bg-gray-100",
  "bg-gray-900",
  "bg-blue-500",
  "bg-blue-600",
  "bg-blue-700",
  "bg-indigo-500",
  "bg-indigo-600",
  "bg-indigo-700",
  "bg-purple-500",
  "bg-purple-600",
  "bg-purple-700",
  "bg-green-500",
  "bg-green-600",
  "bg-green-700",
  "bg-teal-500",
  "bg-teal-600",
  "bg-teal-700",
  "bg-red-500",
  "bg-red-600",
  "bg-red-700",
  "bg-orange-500",
  "bg-orange-600",
  "bg-orange-700",
  "bg-yellow-500",
  "bg-yellow-600",
  "bg-yellow-700",
  "bg-pink-500",
  "bg-pink-600",
  "bg-pink-700",
  "bg-gray-500",
  "bg-gray-600",
  "bg-gray-700",
];

export const titleFontSizes = [
  { name: "XL", value: "text-xl" },
  { name: "2XL", value: "text-2xl" },
  { name: "3XL", value: "text-3xl" },
  { name: "4XL", value: "text-4xl" },
  { name: "5XL", value: "text-5xl" },
  { name: "6XL", value: "text-6xl" },
  { name: "7XL", value: "text-7xl" },
  { name: "8XL", value: "text-8xl" },
  { name: "9XL", value: "text-9xl" },
];

export const contentFontSizes = [
  { name: "XS", value: "text-xs" },
  { name: "SM", value: "text-sm" },
  { name: "Base", value: "text-base" },
  { name: "LG", value: "text-lg" },
  { name: "XL", value: "text-xl" },
  { name: "2XL", value: "text-2xl" },
];

export const titleFontFamilies = [
  { name: "Roboto", value: "font-roboto" },
  { name: "Open Sans", value: "font-open-sans" },
  { name: "Lato", value: "font-lato" },
  { name: "Montserrat", value: "font-montserrat" },
  { name: "Oswald", value: "font-oswald" },
  { name: "Raleway", value: "font-raleway" },
  { name: "Merriweather", value: "font-merriweather" },
  { name: "Playfair Display", value: "font-playfair-display" },
  { name: "Poppins", value: "font-poppins" },
  { name: "Nunito", value: "font-nunito" },
  { name: "Mukta", value: "font-mukta" },
  { name: "Alegreya", value: "font-alegreya" },
  { name: "Quicksand", value: "font-quicksand" },
  { name: "Source Sans Pro", value: "font-source-sans-pro" },
  { name: "Fjalla One", value: "font-fjalla-one" },
];

export const contentFontFamilies = [
  { name: "Arial", value: "font-arial" },
  { name: "Verdana", value: "font-verdana" },
  { name: "Tahoma", value: "font-tahoma" },
  { name: "Georgia", value: "font-georgia" },
  { name: "Palatino", value: "font-palatino" },
  { name: "Garamond", value: "font-garamond" },
  { name: "Times New Roman", value: "font-times-new-roman" },
  { name: "Courier New", value: "font-courier-new" },
  { name: "Helvetica", value: "font-helvetica" },
  { name: "Lucida Sans", value: "font-lucida-sans" },
];
